# Generated by Django 2.2 on 2019-05-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190521_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incart', to='cart.Cart', verbose_name='Корзина'),
        ),
    ]
