# Generated by Django 2.2 on 2019-06-06 17:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='authuser', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Аватарка')),
                ('phone', models.CharField(help_text='+375*********', max_length=16, verbose_name='Контактный телефон')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='Индекс')),
                ('address1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес1')),
                ('address2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес2')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
