# Generated by Django 2.2 on 2019-04-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default=11, max_length=100, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
