# Generated by Django 2.2 on 2019-06-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190607_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='catalog.Author', verbose_name='Авторы'),
        ),
    ]
