# Generated by Django 2.2 on 2019-04-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=11, upload_to='images', verbose_name='Обложка'),
            preserve_default=False,
        ),
    ]
