# Generated by Django 2.2 on 2019-04-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
