# Generated by Django 2.2 on 2019-04-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190412_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.Publish', verbose_name='Издательство'),
        ),
    ]
