# Generated by Django 2.2 on 2019-05-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20190515_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Обложка'),
        ),
    ]
