# Generated by Django 2.2 on 2019-06-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='ФИО')),
                ('phone', models.CharField(help_text='+', max_length=16, verbose_name='Контактный телефон')),
                ('email', models.EmailField(blank=True, help_text='user@mail.com', max_length=254, null=True, verbose_name='Электронная почта')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incart', to='cart.Cart', verbose_name='Корзина')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.OrderStatus', verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
