# Generated by Django 2.2 on 2019-05-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='+', max_length=16, verbose_name='Контактный телефон'),
        ),
    ]
