# Generated by Django 2.2 on 2019-04-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authortable',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authortable',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='publish',
            name='year_publish',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='isbn',
        ),
        migrations.AddField(
            model_name='authortable',
            name='name',
            field=models.CharField(default=11, max_length=100, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publish',
            name='city',
            field=models.CharField(default=11, max_length=30, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='description',
            field=models.TextField(default=11, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=30, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='name_publish',
            field=models.CharField(max_length=30, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='series',
            field=models.CharField(max_length=100, verbose_name='Серия'),
        ),
    ]
