# Generated by Django 2.2 on 2019-04-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190408_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='authortable',
            name='description',
            field=models.TextField(default=11, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
