# Generated by Django 2.2 on 2019-04-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_authortable_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorTable',
            new_name='Author',
        ),
    ]
