# Generated by Django 2.2 on 2019-04-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190408_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publish',
            old_name='city',
            new_name='description',
        ),
    ]
