# Generated by Django 2.2 on 2019-04-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190409_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='binding',
            options={'verbose_name': 'Переплет', 'verbose_name_plural': 'Переплеты'},
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серии'},
        ),
    ]
