# Generated by Django 2.2 on 2019-04-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190409_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publish',
            options={'verbose_name': 'Издательство', 'verbose_name_plural': 'Издательства'},
        ),
    ]
